cmake_minimum_required(VERSION 3.8)
project(vendor_robot_moveit_config)
find_package(ament_cmake REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(moveit_ros_planning_interface REQUIRED)
find_package(moveit_msgs REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rclcpp_action REQUIRED)
find_package(vendor_robot_msgs REQUIRED)
add_executable(move_l_action_server src/move_l_action_server.cpp)
target_compile_features(move_l_action_server PUBLIC cxx_std_17)
target_compile_options(move_l_action_server PRIVATE -Wall -Wextra -Wpedantic)
ament_target_dependencies(move_l_action_server geometry_msgs moveit_ros_planning_interface
  moveit_msgs rclcpp rclcpp_action vendor_robot_msgs)
install(TARGETS move_l_action_server DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY config launch DESTINATION share/${PROJECT_NAME})
ament_package()
