cmake_minimum_required(VERSION 3.8)
project(vendor_robot_controllers)
find_package(ament_cmake REQUIRED)
find_package(controller_interface REQUIRED)
find_package(controller_manager_msgs REQUIRED)
find_package(diagnostic_msgs REQUIRED)
find_package(pluginlib REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rclcpp_lifecycle REQUIRED)
find_package(realtime_tools REQUIRED)
find_package(std_srvs REQUIRED)
find_package(std_msgs REQUIRED)
find_package(vendor_robot_sdk_vendor REQUIRED)
find_package(vendor_robot_driver_core REQUIRED)
find_package(vendor_robot_msgs REQUIRED)
add_library(${PROJECT_NAME} SHARED
  src/io_and_status_controller.cpp src/driver_status_broadcaster.cpp
  src/speed_scaling_broadcaster.cpp)
target_compile_features(${PROJECT_NAME} PUBLIC cxx_std_17)
target_compile_options(${PROJECT_NAME} PRIVATE -Wall -Wextra -Wpedantic)
target_include_directories(${PROJECT_NAME} PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
  $<INSTALL_INTERFACE:include>)
ament_target_dependencies(${PROJECT_NAME}
  controller_interface pluginlib rclcpp rclcpp_lifecycle realtime_tools std_msgs
  vendor_robot_driver_core vendor_robot_msgs)
pluginlib_export_plugin_description_file(controller_interface vendor_robot_controllers.xml)
install(TARGETS ${PROJECT_NAME} DESTINATION lib)
add_executable(sdk_manager_node src/sdk_manager_node.cpp)
target_compile_features(sdk_manager_node PUBLIC cxx_std_17)
target_compile_options(sdk_manager_node PRIVATE -Wall -Wextra -Wpedantic)
ament_target_dependencies(sdk_manager_node rclcpp std_srvs vendor_robot_msgs)
target_link_libraries(sdk_manager_node vendor_robot_sdk_vendor::cr_sdk)
set_target_properties(sdk_manager_node PROPERTIES INSTALL_RPATH "$ORIGIN/..")
install(TARGETS sdk_manager_node DESTINATION lib/${PROJECT_NAME})
add_executable(diagnostics_bridge_node src/diagnostics_bridge_node.cpp)
ament_target_dependencies(diagnostics_bridge_node diagnostic_msgs rclcpp vendor_robot_msgs)
install(TARGETS diagnostics_bridge_node DESTINATION lib/${PROJECT_NAME})
add_executable(controller_stopper_node src/controller_stopper_node.cpp)
ament_target_dependencies(controller_stopper_node
  controller_manager_msgs rclcpp vendor_robot_msgs)
install(TARGETS controller_stopper_node DESTINATION lib/${PROJECT_NAME})
add_executable(controller_bootstrapper_node src/controller_bootstrapper_node.cpp)
target_compile_features(controller_bootstrapper_node PUBLIC cxx_std_17)
target_compile_options(controller_bootstrapper_node PRIVATE -Wall -Wextra -Wpedantic)
ament_target_dependencies(controller_bootstrapper_node controller_manager_msgs rclcpp)
install(TARGETS controller_bootstrapper_node DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY include/ DESTINATION include)
install(FILES vendor_robot_controllers.xml DESTINATION share/${PROJECT_NAME})
ament_package()
